services:
  web:
    build:
      context: .
      target: ${TARGET:-development}
      args:
        DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - db
    volumes:
      - ./:/usr/src/app
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

volumes:
  postgres_data:
