services:
  web:
    image: index.docker.io/lvccrespo/cacrespo-website:latest
    build:
      context: .
      target: ${TARGET:-production}
      args:
        DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
        LOGFIRE_TOKEN: ${LOGFIRE_TOKEN}
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      HISTFILE: /root/hist/.bash_history
    volumes:
      - /usr/src/app/.venv
      - ./:/usr/src/app
      - shell_history:/root/hist
  db:
    image: postgres:15
    environment:
      HISTFILE: /root/hist/.bash_history
      DATABASE_URL: ${DATABASE_URL}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - shell_history:/root/hist
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup --interval 60
    profiles: ["production"]

volumes:
  postgres_data:
  shell_history:
