services:
  web:
    build:
      context: .
      target: ${TARGET:-development}
      args:
        DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      HISTFILE: /root/hist/.bash_history
    volumes:
      - ./:/usr/src/app
      - shell_history:/root/hist
  db:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      HISTFILE: /root/hist/.bash_history
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - shell_history:/root/hist

volumes:
  postgres_data:
  shell_history:
