version: '3.8'

services:
  web:
    build: .
    command: >
+      sh -c "python manage.py collectstatic --no-input &&
+      gunicorn mysite.wsgi:application --bind 0.0.0.0:80"
    ports:
      - 80:80
    env_file:
      - ./.env
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=mysite.settings.prod
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      - PGUSER=my_user
      - POSTGRES_DB=my_site_prod
      - POSTGRES_USER=my_user
      - POSTGRES_PASSWORD=my_site

volumes:
  postgres_data:
