# Generated by Django 5.0.8 on 2025-08-31 23:19

from django.db import migrations
from pgvector.django import VectorExtension


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_vector"),
    ]

    operations = [VectorExtension()]
