# Generated by Django 5.0.8 on 2025-09-02 00:27

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_pgvector"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="embedding",
            field=pgvector.django.vector.VectorField(dimensions=512, editable=False, null=True),
        ),
    ]
