# Generated by Django 5.0.8 on 2025-09-03 00:47

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_embedding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='vector',
        ),
        migrations.AddField(
            model_name='article',
            name='embedding',
            field=pgvector.django.vector.VectorField(default=1, dimensions=512, editable=False),
            preserve_default=False,
        ),
    ]
