# This workflow builds and pushes a new Docker image to Docker Hub.
# The actual deployment happens automatically because the server uses Watchtower
# to update the running container whenever a new image is published.

name: Deploy to Production

on:
  workflow_run:
    workflows: ["Django CI"]
    types:
      - completed
    branches:
      - main

jobs:
  build-and-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Build and Push Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: production
          push: true
          tags: |
            lvccrespo/cacrespo-website:latest
            lvccrespo/cacrespo-website:${{ github.sha }}
